language: node_js
node_js:
  - '6'

deploy:
  provider: npm
  email: unindented@gmail.com
  api_key:
    secure: KtlB4jwkf4faKoBWOztL4bQyg7Tqc4fW0zSYefQyr2qsEfz89v7SOEhZQ4Y3npc1EeTLKK0Q3bnKLlsh22TfeJWHid4snSgLmC8H6yGtGBPuGfskKCfAYlVhSr3pbpFeKZyvfJVrLHjq9iE6ks8fdZ/5IIY/fOb1htaMPtPpLAE=
  on:
    tags: true
